class Const:
    PUSH_TYPE_NONE = 0
    PUSH_TYPE_ORDER = 1
    PUSH_TYPE_MESSAGE = 2
    PUSH_TYPE_ORDER_BOARD = 3
    PUSH_TYPE_BOARD = 4
    PUSH_TYPE_BAD_COMPANY = 5
    PUSH_TYPE_NEWS = 6
    PUSH_TYPE_WORK_PHOTO = 7
    PUSH_TYPE_POINT = 8
